config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :genres
  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favourites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy]

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres, dependent: :destroy
  has_many :movies, through: :movie_genres

  validates :name, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin, except: [:index, :show]

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, notice: "Genre successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(movie_params)
      redirect_to genres_path, notice: "Genre successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to movies_path, status: :see_other,
      danger: "Genre successfully delete!"
  end

private

  def genre_params
    params.require(:genre).
      permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %>

    <%= render "shared/errors", object: genre %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing <%= @genre.name %></h1>

<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h1><%= pluralize(@genres.size, "Genre") %></h1>
<ul class="users">
  <% @genres.each do |genre| %>
    <li>
      <%= link_to genre.name, genre %>
      created
      <%= time_ago_in_words(genre.created_at) %> ago
    </li>
  <% end %>
</ul>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Genre", new_genre_path, class: "button" %>
  </section>
<% end %>

app/views/genres/new.html.erb
<h1>Create A New Genre</h1>

<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>