config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :genres
  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favourites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy]

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
  <%= puts content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
    Copyright &copy; <%= Time.now.year %>
    <%= link_to "The Pragmatic Studio", "https://pragmaticstudio.com" %>
    </p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
        <li>
            <%= nav_link_to "Released", movies_path %>
        </li>
        <li>
            <%= nav_link_to 'Upcoming', filtered_movies_path(:upcoming) %>
        </li>
        <li>
            <%= nav_link_to 'Recent', filtered_movies_path(:recent) %>
        </li>
        <li>
            <%= nav_link_to "Hits", filtered_movies_path(:hits) %>
        </li>
        <li>
            <%= nav_link_to "Flops", filtered_movies_path(:flops) %>
        </li>
    </ul>
    <ul class="right">
        <% if current_user %>
            <li>
                <%= link_to current_user.name, current_user %>
            </li>
            <li>
                <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "button" %>
            </li>
        <% else %>
            <li>
                <%= link_to "Sign In", new_user_session_path, class: "button"  %>
            </li>
            <li>
                <%= link_to "Sign Up", new_user_registration_path, class: "button" %>
            </li>
        <% end %>
    </ul>
    </nav>      
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>